Implementing KNN Algorithm with Scikit-Learn

# The Dataset

## Importing Libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the Dataset

In [12]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

dataset

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

## Preprocessing

In [5]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

#The X variable contains the first four columns of the dataset (i.e. attributes) while y contains the labels.

# Buid KNN

## Train Test Split

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

## Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## Training and Predictions

In [15]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
y_pred

array(['Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype=object)

### Unlabel Prediction

In [28]:
Unlabel_url = "Dataset\iris_unlabel.csv"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

unlabel_data = pd.read_csv(Unlabel_url, names=names)
unlabel_data


sepal-length  sepal-width  petal-length  petal-width Class
0           6.6          2.9           4.6          1.3     ?
1           6.1          2.6           5.6          1.4     ?
2           6.9          3.2           5.7          2.3     ?
3           5.0          3.6           1.4          0.2     ?
4           7.7          3.8           6.7          2.2     ?
5           5.5          2.5           4.0          1.3     ?
6           6.6          3.0           4.4          1.4     ?
7           5.0          3.5           1.6          0.6     ?
8           5.0          3.0           1.6          0.2     ?
9           6.4          2.8           5.6          2.1     ?

In [29]:
X_unlabel = unlabel_data.iloc[:, :-1].values
y_unlabel = unlabel_data.iloc[:, 4].values

array([[6.6, 2.9, 4.6, 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.9, 3.2, 5.7, 2.3],
       [5. , 3.6, 1.4, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [5.5, 2.5, 4. , 1.3],
       [6.6, 3. , 4.4, 1.4],
       [5. , 3.5, 1.6, 0.6],
       [5. , 3. , 1.6, 0.2],
       [6.4, 2.8, 5.6, 2.1]])

In [33]:
y_unlabel_pred = classifier.predict(X_unlabel)
y_unlabel_pred

array(['Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype=object)

## Evaluating the Algorithm

In [19]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 0  8  1]
 [ 0  1 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.89      0.89      0.89         9
 Iris-virginica       0.91      0.91      0.91        11

       accuracy                           0.93        30
      macro avg       0.93      0.93      0.93        30
   weighted avg       0.93      0.93      0.93        30

